name: germplasmx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.2.0  
  provider: ^6.0.5
  file_selector: ^1.0.3
  path_provider: ^2.1.2
  qr_flutter: ^4.0.0
  csv: ^5.1.1
  uuid: ^3.0.7  # You can upgrade to ^4.0.0+ if you need null-safe enhancements
  permission_handler: ^11.0.1
  screenshot: ^2.1.0
  universal_html: ^2.2.3
  pdf: ^3.10.4
  printing: ^5.14.2
  image_picker: ^1.0.4
  js: ^0.6.7
  google_mlkit_barcode_scanning: ^0.11.0
  google_mlkit_commons: ^0.7.1
  fl_chart: ^0.64.0
  android_intent_plus: ^4.0.3
  intl: ^0.18.1
  external_path: ^2.2.0
  mobile_scanner: ^6.0.10
  share_plus: ^11.0.0
  http: ^1.4.0
  file_picker: ^10.2.0
  flutter_launcher_icons: "^0.14.4"
  flutter_screenutil: ^5.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
